# Generated by Django 5.0.1 on 2025-01-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0011_remove_reaction_prods_edited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="stereo_counts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reaction",
            name="stereo_locations_list",
            field=models.TextField(blank=True, null=True),
        ),
    ]
