# Generated by Django 5.0.1 on 2025-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0013_reactiontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="templates",
            field=models.ManyToManyField(
                blank=True,
                related_name="created_by_users",
                to="reactions.reactiontemplate",
            ),
        ),
    ]
