# Generated by Django 5.0.1 on 2025-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0014_user_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="reaction_signature",
            field=models.TextField(
                blank=True,
                help_text="Unique identifier for reaction matching",
                null=True,
            ),
        ),
    ]
