# Generated by Django 5.0.1 on 2025-02-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0016_reaction_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="reactiontemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
