# Generated by Django 5.0.1 on 2025-02-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0017_reactiontemplate_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedMetabolite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("inchi_key", models.CharField(max_length=27, unique=True)),
                ("mol_file", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("draw", "Draw"),
                            ("mol_file", "MDL Mol File"),
                            ("user_input", "User Input"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "original_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_metabolites",
                        to="reactions.user",
                    ),
                ),
            ],
        ),
    ]
