# Generated by Django 5.0.1 on 2025-02-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0018_savedmetabolite"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmetabolite",
            name="vmh_abbr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="savedmetabolite",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("draw", "Draw"),
                    ("mol_file", "MDL Mol File"),
                    ("chebi", "ChEBI"),
                    ("swisslipids", "SwissLipids"),
                    ("pubchem", "PubChem"),
                ],
                max_length=50,
            ),
        ),
    ]
