# Generated by Django 5.0.1 on 2025-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0019_savedmetabolite_vmh_abbr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmetabolite",
            name="inchi",
            field=models.TextField(blank=True, null=True),
        ),
    ]
