# Generated by Django 5.0.1 on 2025-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0020_savedmetabolite_inchi"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmetabolite",
            name="mol_w",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="smiles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
