# Generated by Django 5.0.1 on 2025-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0021_savedmetabolite_mol_w_savedmetabolite_smiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmetabolite",
            name="mol_formula",
            field=models.TextField(blank=True, null=True),
        ),
    ]
