# Generated by Django 5.0.1 on 2025-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0022_savedmetabolite_mol_formula"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmetabolite",
            name="biggId",
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="biocyc",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="casRegistry",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="cheBlId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="chembl",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="chemspider",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="chodb_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="drugbank",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="echa_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="ehmnId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="epa_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="fda_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="food_db",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="hepatonetId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="hmdb",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="iupac",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="iuphar_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="keggId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="knapsack",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="lmId",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="mesh_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="metanetx",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="metlin",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="monoisotopicweight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="pdmapName",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="pubChemId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="seed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="wikipedia",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
