# Generated by Django 5.0.1 on 2025-02-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0023_savedmetabolite_biggid_savedmetabolite_biocyc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedmetabolite",
            name="monoisotopicweight",
        ),
        migrations.RemoveField(
            model_name="savedmetabolite",
            name="user",
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_metabolites",
                to="reactions.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedmetabolite",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_metabolites", to="reactions.user"
            ),
        ),
    ]
