# Generated by Django 5.0.1 on 2025-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0024_remove_savedmetabolite_monoisotopicweight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="metabolite_inchi_keys",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reaction",
            name="metabolite_inchis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reaction",
            name="metabolite_mol_weights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reaction",
            name="metabolite_smiles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
