location_mapping = {
    "Apical cell membrane": "[e]",
    "Apicolateral cell membrane": "[e]",
    "Basal cell membrane": "[c]",
    "Basolateral cell membrane": "[c]",
    "Cell junction, focal adhesion": "[c],[e]",
    "Cell membrane": "[c],[e]",
    "Cell projection, lamellipodium": "[c]",
    "Cell projection, neuron projection": "[c],[e]",
    "Cell projection, ruffle": "[c]",
    "Cytoplasm": "[c]",
    "Cytoplasm, perinuclear region": "[c]",
    "Cytoplasmic Granule": "[c]",
    "Cytoplasmic vesicle": "[c]",
    "Cytoplasmic vesicle membrane": "[c],[e]",
    "Cytoplasmic vesicle, phagosome membrane": "[c],[e]",
    "Cytoplasmic vesicle, secretory vesicle, synaptic vesicle": "[c],[e]",
    "Cytosol": "[c]",
    "Endomembrane system": "[c]",
    "Endoplasmic reticulum": "[r]",
    "Endoplasmic reticulum lumen": "[r]",
    "Endoplasmic reticulum membrane": "[r]",
    "Endosome": "[c]",
    "Endosome Membrane": "[c]",
    "Extracellular endosome": "[e]",
    "extracellular region ficolin-1-rich granule lumen": "[e]",
    "Golgi apparatus lumen": "[g]",
    "Golgi apparatus membrane": "[c],[g]",
    "Lipid droplet": "/",
    "Lysosome": "[l]",
    "Melanosome": "[c]",
    "Melanosome membrane": "[c]",
    "Membrane": "[c],[e]",
    "Membrane raft": "[c],[e]",
    "Microsome": "[r]",
    "Microsome membrane": "[r]",
    "Mithocondria": "[m]",
    "Mitochondrion intermembrane space": "[m]",
    "Mitochondrion matrix": "[m]",
    "Mitochondrion membrane": "[c],[m]",
    "Mitochondrion outer membrane": "[c]",
    "Nucleoplasm": "[n]",
    "Nucleus": "[n]",
    "Nucleus membrane": "[c],[n]",
    "Nucleus outer membrane": "[c]",
    "Peroxisome": "[x]",
    "Photoreceptor inner segment": "[c]",
    "Presynapse": "[c]",
    "Secreted": "[e]",
    "Secreted, extracellular space": "[e]",
    "secretory granule lumen": "[e]",
    "Synapse": "[c],[e]",
    "Synapse, synaptosome": "[c],[e]",
    "tertiary granule lumen": "[e]",
    "Type III Intermediate Filament": "[c]",
    "Vacuole membrane": "[c]"
}

ORGAN_MAPPING = {
    "adipose tissue": "Adipocytes",
    "adrenal gland": "Agland",
    "amygdala": "Brain",
    "appendix": "/",
    "basal ganglia": "Brain",
    "bone marrow": "/",
    "breast": "Breast",
    "cerebellum": "Brain",
    "cerebral cortex": "Brain",
    "cervix": "Cervix",
    "choroid plexus": "Brain",
    "colon": "Colon",
    "duodenum": "sIEC",
    "endometrium 1": "Uterus",
    "epididymis": "Testis",
    "esophagus": "Lung",
    "fallopian tube": "Uterus",
    "gallbladder": "Gall",
    "heart muscle": "Heart",
    "hippocampal formation": "Brain",
    "hypothalamus": "Brain",
    "kidney": "Kidney",
    "liver": "Liver",
    "lung": "Lung",
    "lymph node": "/",
    "midbrain": "Brain",
    "ovary": "Ovary",
    "pancreas": "Pancreas",
    "parathyroid gland": "Pthyroidgland",
    "pituitary gland": "/",
    "placenta": "/",
    "prostate": "Prostate",
    "rectum": "Colon",
    "retina": "Retina",
    "salivary gland": "/",
    "seminal vesicle": "Testis",
    "skeletal muscle": "Muscle",
    "skin 1": "Skin",
    "small intestine": "sIEC",
    "smooth muscle": "/",
    "spinal cord": "Scord",
    "spleen": "Spleen",
    "stomach 1": "Stomach",
    "testis": "Testis",
    "thymus": "/",
    "thyroid gland": "Thyroidgland",
    "tongue": "/",
    "tonsil": "/",
    "urinary bladder": "Urinarybladder",
    "vagina": "Cervix"
}
