from django.core.management.base import BaseCommand
from reactions.models import ReactionTemplate


class Command(BaseCommand):
    """
    Management command to load all default reaction templates into the database.
    """
    help = "Load all default reaction templates into the database"

    def handle(self, *args, **kwargs):
        DEFAULT_TEMPLATES = {
            'hydrolysis': {
                'substrates': 'empty,h2o,h',
                'products': 'empty,empty,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1,1',
                'prods_sch': '1,1,1',
            },
            'O2NADPHOX': {
                'substrates': 'empty,o2,nadph,h',
                'products': 'empty,h2o,nadp',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh,vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-,-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1,1,1',
                'prods_sch': '1,1,1',
            },
            'SULT': {
                'substrates': 'empty,paps',
                'products': 'empty,pap,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1,1',
            },
            'UGT': {
                'substrates': 'empty,udpglcur',
                'products': 'empty,udp,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1,1',
            },
            'UGT glucose': {
                'substrates': 'empty,udpg',
                'products': 'empty,udp,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1,1',
            },
            'UGT carb glucur': {
                'substrates': 'empty,udpglcur,co2',
                'products': 'empty,udp,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1,1',
                'prods_sch': '1,1,1',
            },
            'CoA': {
                'substrates': 'empty,coa,atp',
                'products': 'empty,amp,ppi',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1,1',
                'prods_sch': '1,1,1',
            },
            'FAOXhd': {
                'substrates': 'empty,h2o',
                'products': 'empty',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-',
                'subs_sch': '1,1',
                'prods_sch': '1',
            },
            'FAOXnad': {
                'substrates': 'empty,nad',
                'products': 'empty,nadh,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1,1',
            },
            'FAOXcoa': {
                'substrates': 'empty,coa',
                'products': 'empty,accoa',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1',
            },
            'Nad ox': {
                'substrates': 'empty,nad',
                'products': 'empty,nadh,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1,1',
            },
            'NADH red': {
                'substrates': 'empty,nadh,h',
                'products': 'empty,nad',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh,vmh',
                'products_types': 'vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-,-',
                'prods_comps': '-,-',
                'subs_sch': '1,1,1',
                'prods_sch': '1,1',
            },
            'cycl': {
                'substrates': 'empty,h',
                'products': 'empty,h2o',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1',
            },
            'NADPH red': {
                'substrates': 'empty,nadph,h',
                'products': 'empty,nadp',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh,vmh',
                'products_types': 'vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-,-',
                'prods_comps': '-,-',
                'subs_sch': '1,1,1',
                'prods_sch': '1,1',
            },
            'AT': {
                'substrates': 'taur,empty',
                'products': 'empty,coa,h',
                'direction': 'forward',
                'substrates_types': 'vmh,vmh',
                'products_types': 'vmh,vmh,vmh',
                'subsystem': 'undefined',
                'subs_comps': '-,-',
                'prods_comps': '-,-,-',
                'subs_sch': '1,1',
                'prods_sch': '1,1,1',
            },
        }

        for name, template_data in DEFAULT_TEMPLATES.items():
            ReactionTemplate.objects.update_or_create(
                name=name,
                is_default=True,
                user=None,
                defaults=template_data
            )
        self.stdout.write(self.style.SUCCESS(
            'All default templates loaded successfully!'))
